# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # push frontend docker image
      - uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: RIckyBan/gaming-hoge-generator/frontend
          tag: latest
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GAMING_CR_PAT  }}
          dockerfile: frontend/nginx/Dockerfile
          directory: frontend
  
      # push backend docker image
      - uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: RIckyBan/gaming-hoge-generator/backend
          tag: latest
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GAMING_CR_PAT }}
          dockerfile: backend/Dockerfile
          directory: backend
